### ISSUE TITLE
请教一下，登陆access denied

### ISSUE THREAD

**Issue by hobocow** [zhaojunlike/nike-snkrs-api#6]
你好，

我用chrome浏览nike官网然后把里面的_abck 数据拿出来， 之后把这个数据加到requests cookies里然后访问 ：

https://unite.nike.com/login?appVersion=630&experienceVersion=528&uxid=com.nike.commerce.snkrs.web&locale=fr_FR&backendEnvironment=identity&browser=Google%20Inc.&os=undefined&mobile=false&native=false&visit=1&visitor="+str(uuid.uuid4())

但是现在老是access denied。。。请问可以指明一下吗 汉语说得不是很好。。。谢谢！

**Comment by zhaojunlike** [comment]
wow, haha, just post akamai sensor-data to the api `xxx.com/${hashId}`  body: {sensor_data:''''}

**Comment by hobocow** [comment]
你好，非常感谢解答，我已经搞了好几个小时了 :D 

您的意思是 登陆unite.nike.com 之前，先把{"sensor_data":"7a74G7 这个开头的data, post 到 https://www.nike.com/static/3cb9392605c182d932fab637185737d 吗？ 我之前好像是过了但是不太行。。

谢谢！
